<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Applications_of_Linear_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Systems of Linear Equations

### Systems of Linear Equations can be solved with arrays and Numpy

In [3]:
import numpy as np

A = np.array([[4,5],[3,-2]])
B = np.array([[7],[11]])

X = np.linalg.inv(A).dot(B)
print(X)

[[ 3.]
 [-1.]]


In [5]:
G = np.linalg.solve(A,B)
print(G)


[[ 3.]
 [-1.]]


In [9]:
from scipy.linalg import solve

J = solve(A,B)
print(J)


[[ 3.]
 [-1.]]
