<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Codng_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# CODING ACTIVITY 3



Create a Python program that applies an inverse of 3x3 or 4x4 matrix and apply also its transpose.

In [10]:
import numpy as np

#3x3 matix
a=np.array([[4,5,5],[2,9,0],[3,4,7]])
print("3x3 matrix")
print(a,"\n")

#inverse of 3x3 matrix
inva = (np.linalg.inv(a))
print("Inverse of the 3x3 matrix")
print(inva,"\n")

#transpose of 3x3 matrix
b = np.transpose(a)
print("Transpose of 3x3 matrix")
print(b)




3x3 matrix
[[4 5 5]
 [2 9 0]
 [3 4 7]] 

Inverse of the 3x3 matrix
[[ 0.72413793 -0.17241379 -0.51724138]
 [-0.16091954  0.14942529  0.11494253]
 [-0.2183908  -0.01149425  0.29885057]] 

Transpose of 3x3 matrix
[[4 2 3]
 [5 9 4]
 [5 0 7]]


In [11]:
import numpy as np

#4x4 matrix
c=np.array([[2,6,4,5],[1,2,6,9],[7,5,3,3],[3,4,5,6]])
print("4x4 matrix")
print(c,"\n")

#inverse of 4x4 matrix
invc = (np.linalg.inv(c))
print("Inverse of the 4x4 matrix")
print(invc,"\n")

#transpose of 4x4 matrix
d = np.transpose(c)
print("Transpose of 4x4 matrix")
print(d)

4x4 matrix
[[2 6 4 5]
 [1 2 6 9]
 [7 5 3 3]
 [3 4 5 6]] 

Inverse of the 4x4 matrix
[[-0.12195122  0.08943089  0.22764228 -0.14634146]
 [ 0.31707317 -0.03252033  0.00813008 -0.2195122 ]
 [-0.56097561 -0.78861789 -0.55284553  1.92682927]
 [ 0.31707317  0.63414634  0.34146341 -1.2195122 ]] 

Transpose of 4x4 matrix
[[2 1 7 3]
 [6 2 5 4]
 [4 6 3 5]
 [5 9 3 6]]
