<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np 
from numpy.linalg import eig


a = np.array([[-12,3],[4,1]])

b = np.array([[0],[0]])


x = np.linalg.solve(a,b)
print(x)

[[-0.]
 [ 0.]]


In [29]:
c = np.array([[-6,3],[4,5]])

w,v = np.linalg.eig(c)

print("eigenvalue:",w)
print("eigenvector:",v)

eigenvalue: [-7.  6.]
eigenvector: [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [42]:
d = np.array([[2,2,4],[1,3,5],[2,3,4]])
print(d)

s,t = np.linalg.eig(d)

print(s.round())
print(t.round())
p = np.dot(d,t.round())
print(p)

[[2 2 4]
 [1 3 5]
 [2 3 4]]
[ 9.  1. -1.]
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
