<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [27]:
import numpy as np



LinAlgError: ignored

# Problem 2. Solve each system: (30 points)

#3x - y + z = 5

#9x - 3y +3z = 15

#12x +4y -4z = -20 

In [25]:
q2a = np.array([[3,1,1],[9,-3,3],[-12,4,-4]])
q2inv = np.linalg.inv(q2a)
q2b = np.array([[5],[15],[20]])
print("inverse of matrix")
print(q2inv,"\n")




LinAlgError: ignored

## *An error is being display because the given matrix is a 'Singular Matrix'. Singular matrices has a determinant of 0. Since the determinant is 0, the inverse can't be found. And since we can't find the inverse of the matrix, we cannot solve for the system.*

# Problem 3. Consider the matrix, (40 points)

In [13]:
#Matrix given
q3a = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print("Matrix Given: \n",q3a,"\n")


#Commands to get the Eigenvalue and Eigenvector
q3w,q3v = np.linalg.eig(q3a)

print("Eigenvalue: \n", q3w.round(),"\n")
print("Eigenvector: \n", q3v.round())

Matrix Given: 
 [[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

Eigenvalue: 
 [-1.  3.  2.] 

Eigenvector: 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
