<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

A = np.array([[4,10,8],[10,26,26],[8,26,61]])

inv_A = np.linalg.inv(A)


In [14]:
B= np.array([[44],[128],[214]])


In [15]:
print(A)
print(inv_A)
print(B)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]
[[ 44]
 [128]
 [214]]


In [16]:
X = np.dot(inv_A,B)
print(X)

[[-8.]
 [ 6.]
 [ 2.]]
