<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

a = np.array([[1,2,3],[5,4,6],[7,8,9]])

inva = (np.linalg.inv(a))

print(inva)

[[-0.66666667  0.33333333  0.        ]
 [-0.16666667 -0.66666667  0.5       ]
 [ 0.66666667  0.33333333 -0.33333333]]


In [12]:
c = np.dot(a, inva)
print(c)

[[ 1.00000000e+00 -1.66533454e-16  5.55111512e-17]
 [ 8.88178420e-16  1.00000000e+00  1.11022302e-16]
 [ 4.44089210e-16 -5.55111512e-17  1.00000000e+00]]


In [13]:
 d = np.transpose(a)
 print(d)

[[1 5 7]
 [2 4 8]
 [3 6 9]]
