<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [11]:
import numpy as np

q1 = np.array([[1,2,3,4,5],[2,7,5,2,5],[4,5,6,7,8],[5,4,5,6,7],[5,13,5,6,7]]) #5x5 matrix
print(q1)

[[ 1  2  3  4  5]
 [ 2  7  5  2  5]
 [ 4  5  6  7  8]
 [ 5  4  5  6  7]
 [ 5 13  5  6  7]]


# Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [7]:
q2 = np.array((1,1,1,1))
q2d = np.diag(q2) #to make the matrix 4x4 and make the elements below the principal diagonal zero
print(q2d)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [43]:
q3a = np.array([[2,3,4],[4,4,5,],[6,5,9]])
q3b = np.transpose(q3a)

print("3x3 Matrix \n")
print(q3a,"\n")
print("Transpose of the 3x3 Matrix \n")
print(q3b)
#I printed out the transpose of the 3x3 matrix to prove that it is symmetrical

3x3 Matrix 

[[2 3 4]
 [4 4 5]
 [6 5 9]] 

Transpose of the 3x3 Matrix 

[[2 4 6]
 [3 4 5]
 [4 5 9]]


# Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [20]:
c = np.array([[1,2,3],[2,3,3],[3,4,-2]])
q4 = np.linalg.inv(c) #command to get the inverse of matrix "c"
print(q4)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


# Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [24]:
q5 = np.linalg.det(c) #command to get the determinant of matrix c
print(q5)

5.000000000000001


# Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [51]:
q6a = np.array([[5,4,1],[10,9,4],[10,13,15]])
q6inv = np.linalg.inv(q6a)
q6b = np.array([[3.4],[8.8],[19.2]])
print("inverse of matrix A")
print(q6inv,"\n")

print("Root of the linear eqaution")
q6 = np.dot(q6inv,q6b) 
print(q6)

inverse of matrix A
[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]] 

Root of the linear eqaution
[[0.2]
 [0.4]
 [0.8]]
