<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
#Practical Lab Exam 1
import numpy as np

# PROBLEM 1

In [62]:
#Problem 1 
W = np.array(([1,3],[2,-2],[3,1]))
X = np.array(([3,2,1],[-1,2,3],[2,-1,1]))
Y = np.array(([1,2,0],[0,-1,2]))
Z = np.array(([0,1],[2,3]))

a = np.dot(w,y)
b = np.add(z,z)
c = np.dot(3,x)

In [ ]:
#a. WY
a = np.dot(W,Y)
print(a)

[[ 1 -1  6]
 [ 2  6 -4]
 [ 3  5  2]]


In [ ]:
#b. Z+Z
b = np.add(Z,Z)
print(b)

[[0 2]
 [4 6]]


In [ ]:
#c. 3X
c = np.dot(3,X)
print(c)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


# PROBLEM 2

In [55]:
#Problem  2

#a. 
l = np.dot(Y,W)**2
print(l)

#The product (YW)2 is not defined: false

[[25  1]
 [16 16]]


In [46]:
#b.
print(np.mat(W)*np.mat(Y)-X)

#false


[[-2 -3  5]
 [ 3  4 -7]
 [ 1  6  1]]


In [60]:
#c.

print(np.dot(Y,W)-Z**2)

#false



[[ 5 -2]
 [ 0 -5]]
