<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])
print('Vector is A',A)
print('Vector is B', B)

Vector is A [4 3]
Vector is B [ 2 -5]


In [14]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

pool = np.array([ball1,ball2])
#pool.shape
#pool.size
pool.ndim

2

In [13]:
print(pool)

[[ 1  2  3]
 [ 0  1 -1]]


In [15]:
R = A+B
print(R)

[ 6 -2]


In [16]:
R = np.add(A,B)

In [17]:
print(R)


[ 6 -2]


In [18]:
R = np.subtract(A,B)
R


array([2, 8])