<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#C=Matrix and Its Operations
import numpy as np

In [14]:
a = np.array(([-5,0],[4,1]))
b = np.array(([6,-3],[2,3]))

In [9]:
sum = a+b

In [10]:
print(sum)

[[ 1 -3]
 [ 6  4]]


In [12]:
difference1 = a - b
print(difference1)


[[-11   3]
 [  2  -2]]


In [13]:
difference2 = b - b
print(difference2)

[[0 0]
 [0 0]]
