<a href="https://colab.research.google.com/github/jnrtnan/Linear-Algebra-58020/blob/main/Vectors_Represention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [11]:
#Diagonal Matrix
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[1 5 9]


In [14]:
#Identity Matrix
f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
#Zero Matrix
g = np.zeros((6,5))
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
#Empty Matrix
h = np.empty((0,5))
print(h)

[]


In [20]:
#Addition of matrix
i = np.array([[1,2,3],[4,5,6]])
j = np.zeros((2,3))
print(i+j)

[[1. 2. 3.]
 [4. 5. 6.]]


In [21]:
#subtraction of matricex
print(i-j)

[[1. 2. 3.]
 [4. 5. 6.]]


In [22]:
i = np.array([[1,2,3],[4,5,6]])
j = np.array([[-1,2,4],[7,4,2]])
print(i)
print(j)


[[1 2 3]
 [4 5 6]]
[[-1  2  4]
 [ 7  4  2]]


In [23]:
print(i-j)

[[ 2  0 -1]
 [-3  1  4]]
